### ISSUE TITLE
End Scores Switched

### ISSUE THREAD

**Issue by FEEFOO666** [AIESydProgYr12021/aie_cpd-SweetChilliMayo#3]
**Description:**
End scores display the incorrect value as it switches with the other player. 

**Priority:** B

**Platforms:** Web & PC

**Build & Environment:** Build 1

**Reproduction:**

1. Load project
2. Click play
3. Click local
4. Complete game
5. Check player scores with their corresponding colours

**Comment by SweetChilliMayo** [comment]
Fixed end scores displaying incorrectly.

**Comment by FEEFOO666** [comment]
Issue resolved & closed.
