### ISSUE TITLE
Side Tokens Clickable

### ISSUE THREAD

**Issue by CaitieDay** [AIESydProgYr12021/aie_cpd-SweetChilliMayo#4]
Description: 
Display Tokens on the side of the boards are now clickable. If clicked the players cannot finish the game and there is no way to exit. 

Priority: B

Platforms:  PC/ Web

Build & Environment: Build 3 - BlackHole.exe

Reproduction: 
1. Load program
2. Click Play
3. Click Local
4. Click any of the side tokens NOT on the main board

**Comment by SweetChilliMayo** [comment]
Removed ability to click side tokens.
